baseurl = http://192.168.100.142/cas
username = admin
password = Telesuite@8765
chromepath = drivers\\chromedriver.exe
msedgepath = drivers\\msedgedriver.exe
firefoxpath = drivers\\geckodriver.exe
#/*****************************************************************/
#DataBase Related Activities
#Setting class name for older version of JDBC 
#SQL server
classNameSQLServer = com.microsoft.sqlserver.jdbc.SQLServerDriver
#MySQL
classNameMySQL = 
#Pattern to connect to sql server: jdbc:sqlserver://Ip address where database hosted;databaseName=DB_name;encrypt=true;trustServerCertificate=true
#Pattern to connect to my sql: jdbc:mysql://Ip address where database hosted/DB_name
dbUrl = jdbc:sqlserver://192.168.100.148:1433;databaseName=Logger;encrypt=true;trustServerCertificate=true;
userNameForDbConnection = sa
passwordForDbConnection = tsl@875
#/*****************************************************************/
dashboardPageURL = /dashboard
callBillingPageURL = /setup/call
pbxMasterPageURL = /setup/pbx
locationPropertiesPageURL = /setup/locationproperties
rolesPageURL = /roles
usersPageURL = /user
extensionPageURL = /extension
#/*****************************************************************/
loginSnackBar = User logged in successfully.
invalidUsernameOrPassword = Invalid username or password. Please try again.
addRegionSnackbar = Region saved successfully!
addBillingClassSnackbar = Billing Class saved successfully!
addBillingExceptionSnackbar = BillingException saved successfully!
addLocationPropertiesSnackbar = Location & Properties created successfully.
addPbxSnackbar = Pbx saved successfully!
addRolesSnackbar = Role created successfully
deleteBillingClassSnackbar = Billing class deleted successfully
deleteBillingExceptionSnackbar = Billing Exception deleted successfully
deleteLocationPropertiesSnackbar = Properties deleted successfully.
deletePbxSnackbar = Pbx data deleted successfully
deleteRegionSnackbar = deleted successfully
updateBillingClassSnackbar = Billing Class Updated successfully!
updateBillingExceptionSnackbar = BillingException Updated successfully!
updateLocationPropertiesSnackbar = Location & Properties updated successfully.
updatePbxSnackbar = Pbx updated successfully!
updateRegionSnackbar = Region Updated successfully!
updateRolesSnackbar = Role updated successfully
deleteRolesSnackbar = Role deleted successfully
addUsersSnackbar = User Create successfully
updateUserSnackbar = User Update successfully
deleteUserSnackbar = User deleted successfully
addExtensionSnackbar = Extensions created successfully!
#/****************************Regions*************************************/
countryName = India
countryCode = +91
IDD = 12
NDD = 13
areacode = 123
fixedLineStartDigits = 1,2,3
mobileStartDigits = 4,5,6
serviceProviderName = AIRTEL
networkStartDigits = 123
#/****************************Billing Class*************************************/
billingClass = Pallavi
gracePeriod = 1
pulseInSeconds = 1
chargePerPulse = 1
markupPercentage = 1
surcharge = 1
#/****************************Billing Exception*************************************/
tollFreeNumber = 1234
description = Testing
#/****************************PBX*************************************/
pbxName = Pallavi
extensionStartPosition = 
extensionWidth = 
extensionFormat = 
dateAndTimeStartPosition = 
dateAndTimeWidth = 
dateAndTimeFormat = 
durationStartPosition = 
durationWidth = 
durationFormat = 
trunkStartPosition = 
trunkWidth = 
trunkFormat = 
callDirectionStartPosition = 
callDirectionwidth = 
callDirectionFormat = 
dialedNumberStartPosition = 
dialedNumberWidth = 
dialedNumberFormat = 
pulsesStartPosition = 
pulsesWidth = 
pulsesFormat = 
recordSeperatorStartPosition = 
recordSeperatorWidth = 
recordSeperatorFormat = 
accountCodeStartPosition = 
accountCodeWidth = 
accountCodeFormat = 
CLIStartPosition = 
CLIWidth = 
CLIFormat = 
swapExtOrCLIForIncomingCallStartPosition = 
swapExtOrCLIForIncomingCallWidth = 
swapExtOrCLIForIncomingCallFormat = 
columnDelimiterStartPosition = 
columnDelimiterWidth = 
columnDelimiterFormat = 
#/****************************Location Properties*************************************/
locationName = Bengaluru
cdrFilePath = c:/abcde
cdrFileExtension = .txt 
cdrDumpFilePath = c:/qwert
communicationMode = file
connectionMode = client
ipAddress = 1.1.1.1
ipPort = 1234
retryInterval = 1 
comPort = 12345
baudRate = 2
parity = 22
dataBit = 222
stopBit = 2222
#/****************************Roles Page*************************************/
roleName = Testing
#/****************************Roles Page*************************************/
user = Pallavi
displayName = Pallavi
userPassword = Telesuite@8765
userEmail = pallavi@telesoftlabs.com
#/****************************Extensions Page*************************************/
fromExtension = 100
toExtension = 
extensionUsername = Pallavi
trunkName = JIO
#/****************************Search Page*************************************/
searchLocation = Bengaluru
searchDirection = Incoming
searchDuration = Any
searchCallType = Local
searchExtension = 
searchTrunk = 
searchDialedNumber = 
#/****************************Dashboard Page(DD/*************************************/
fromDate = 01/Feb/2026
toDate = 06/Apr/2026