handlers= java.util.logging.ConsoleHandler, java.util.logging.FileHandler
.level= INFO

# ConsoleHandler configuration
java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = CustomTimestampFormatter

# FileHandler configuration
java.util.logging.FileHandler.level = INFO
java.util.logging.FileHandler.pattern = %h/java%u.log
java.util.logging.FileHandler.formatter = CustomTimestampFormatter
